//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by exe.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXE_DIALOG                  102
#define IDS_FILTERDLG                   102
#define IDD_MAIN_DIALOG                 102
#define IDS_APPDLG                      103
#define IDS_LOGINFO                     104
#define IDS_SEARCHLOG                   105
#define IDS_CONFIG                      106
#define IDS_LH_NAME                     107
#define IDS_LH_APP_NAME                 107
#define IDS_LH_PATH                     108
#define IDS_LH_APP_PATH                 108
#define IDS_FN_APPRULE                  109
#define IDS_MB_SURE_DELETE              110
#define IDS_MB_DELETE_FAILURE           111
#define IDS_MB_ERROR_INPUT              112
#define IDS_MB_ERROR_FILEOPEN           113
#define IDS_MB_ERROR_INITPFW            114
#define IDS_LH_LOG_TIME                 115
#define IDS_LH_LOG_ACTION               116
#define IDS_LH_LOG_NAME                 117
#define IDS_LH_LOG_PROTO                118
#define IDS_LH_LOG_DIRECT               119
#define IDS_LH_LOG_LPORT                120
#define IDS_LH_LOG_RIP                  121
#define IDS_LH_LOG_RPORT                122
#define IDS_FORMAT_TIME                 123
#define IDS_ACTION_PASS                 124
#define IDS_ACTION_DENY                 125
#define IDS_DIRECT_IN                   126
#define IDS_DIRECT_OUT                  127
#define IDR_MAINFRAME                   128
#define IDS_BTNTXT_LOGENABLE            128
#define IDR_MAINMENU                    129
#define IDS_BTNTXT_LOGDISABLE           129
#define IDR_MENU1                       130
#define IDR_NOTIFYMENU                  130
#define IDS_BTNTXT_SCROLLENBALE         130
#define IDS_BTNTXT_SCROLLENABLE         130
#define IDD_FILTER_DIALOG               131
#define IDS_BTNTXT_SCROLLDISABLE        131
#define IDI_FILTER_DLG                  132
#define IDS_OFN_FILTER_LOG              132
#define IDI_APP_DLG                     133
#define IDS_LH_FILTER_ACTION            133
#define IDD_APP_DIALOG                  134
#define IDS_LH_FILTER_NAME              134
#define IDD_LOG_DIALOG                  135
#define IDS_LH_FILTER_DESCRIPTION       135
#define IDD_CONFIG_DIALOG               136
#define IDS_FORMAT_TRAYINFO_DENY        136
#define IDD_FIND_DIALOG                 137
#define IDS_FORMAT_TRAYINFO_PASS        137
#define IDI_LOG_INFO                    138
#define IDS_FN_FILTERRULE               138
#define IDI_LOG_DLG                     138
#define IDI_SEARCH_LOG                  139
#define IDS_ACTION_CONTINUE             139
#define IDI_CONFIG                      140
#define IDS_ADDR_TYPE_ANY               140
#define IDI_CONFIG_DLG                  140
#define IDD_APPRULE_INFO                141
#define IDS_ADDR_TYPE_LAN               141
#define IDI_ACTION_PASS                 142
#define IDS_ADDR_TYPE_SPEC              142
#define IDI_ACTION_DENY                 143
#define IDS_ADDR_TYPE_NETWORK           143
#define IDI_ACTION_CONTINUE             144
#define IDS_ACTION_CONTINUE_EX          144
#define IDS_PORT_RANG_LOCAL             145
#define IDS_PORT_RANG_REMOTE            146
#define IDS_REGKEY_AUTORUN              147
#define IDD_FILTERRULE_INFO             148
#define IDS_FN_BEEP                     148
#define IDS_ABOUT                       149
#define IDI_ABOUT_DLG                   149
#define IDC_TABS                        1000
#define IDC_BUTTON1                     1001
#define IDC_CMD_DELETE_APP              1001
#define IDC_CMD_SAVE_LOG                1001
#define IDC_CMD_FILTER_MODIFY           1001
#define IDC_CMD_APPLY_CONFIG            1001
#define IDC_DLG_CTRL                    1003
#define IDC_DLG_LIST                    1005
#define IDC_LIST1                       1006
#define IDC_FILTER_LIST                 1006
#define IDC_APP_LIST                    1008
#define IDC_CMD_MODIFY_APP              1009
#define IDC_CHECK_TCPIN                 1010
#define IDC_CHECK_TCPOUT                1011
#define IDC_CHECK_UDPIN                 1012
#define IDC_CHECK_UDPOUT                1013
#define IDC_RADIO_TCP_RANGE             1014
#define IDC_RADIO_TCP_LIST              1015
#define IDC_EDIT_TCP_PORT1              1016
#define IDC_EDIT_TCP_PORT2              1017
#define IDC_EDIT_TCP_PORTS              1018
#define IDC_RADIO_UDP_RANGE             1019
#define IDC_RADIO_UDP_LIST              1020
#define IDC_EDIT_UDP_PORT1              1021
#define IDC_EDIT_UDP_PORT2              1022
#define IDC_EDIT_UDP_PORTS              1023
#define IDC_CHECK_LOG                   1024
#define IDC_CHECK_FLASH                 1025
#define IDC_CHECK_BEEP                  1026
#define IDC_APPNAME                     1027
#define IDC_APPICON                     1028
#define IDC_LOG_LIST                    1029
#define IDC_CMD_SCROLL_LOG              1030
#define IDC_CMD_CLEAR_LOG               1031
#define IDC_CMD_MONITOR_LOG             1032
#define IDC_CMD_FILTER_DELETE           1033
#define IDC_CMD_FILTER_INSERT           1034
#define IDC_CMD_FILTER_MOVEUP           1035
#define IDC_CMD_FILTER_MOVE_DOWN        1037
#define IDC_EDIT_NAME                   1038
#define IDC_EDIT_DESCRIPTION            1039
#define IDC_DIRECT_OUT                  1040
#define IDC_DIRECT_IN                   1041
#define IDC_IPADDRESS_MASK              1045
#define IDC_IPADDRESS_IP                1046
#define IDC_PROTO_TCP                   1047
#define IDC_PROTO_UDP                   1048
#define IDC_PROTO_IP                    1049
#define IDC_EDIT_PORT1                  1054
#define IDC_EDIT_PORT2                  1055
#define IDC_COMBO_ACTION                1059
#define IDC_CHECK_RECORD                1060
#define IDC_COMBO_IP_TYPE               1063
#define IDC_STATIC_IP                   1064
#define IDC_STATIC_MASK                 1065
#define IDC_PORT_LABEL                  1071
#define IDC_CHECK_AUTO_START            1072
#define IDC_CMD_RESTORE_CONFIG          1073
#define IDC_CHECK_HIDE                  1074
#define ID_CMD_EXIT                     32773
#define ID_CMD_ABOUT                    32774
#define ID_CMD_RESTORE                  32777
#define ID_CMD_FILTERDLG                32782
#define ID_CMD_APPDLG                   32783
#define ID_CMD_LOGINFO                  32787
#define ID_CMD_SEARCH                   32788
#define ID_CMD_CONFIG                   32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
